### ISSUE TITLE
Add integration tests, unit tests and CI

### ISSUE THREAD

**Issue by balsoft** [Terodom/termNote#10]
How about adding some tests and connecting something like Travis CI to this repo? It should be very easy (and reproducible) with nix.

**Comment by balsoft** [comment]
This should be enough for Travis:
`.travis`:
```
language: nix
```

And I can add some tests in default.nix later this day when I have access to my PC.

**Comment by ghost** [comment]
I never worked with Travis, shouldn't the language be cpp?

**Comment by balsoft** [comment]
> I never worked with Travis, shouldn't the language be cpp?

`language: nix` will essentially just run `nix-build`. It will install all the dependencies, run tests, etc. If it builds in travis, it builds everywhere because nix builds are reproducible.

**Comment by ghost** [comment]
But what about the people who don't use nix?

**Comment by balsoft** [comment]
> But what about the people who don't use nix?

They can build it. Nix doesn't do any particular magic when it comes to building - it essentially just calls 
```bash
source $stdenv/setup # Load dependencies
cmake .
make
./test.sh
make install
```
In an isolated and reproducible environment.
If someone has all the needed dependencies installed, they will be able to build it. Using Nix in Travis just simplifies setting up a reproducible build a lot.

**Comment by balsoft** [comment]
So are you going to add CI? I think it will improve ease-to-PR (e.g. it will tell you if there's something wrong with the thing you just PRd)

**Comment by balsoft** [comment]
I think we need to add some unit tests for `todoTxtNote` class.

**Comment by ghost** [comment]
i pushed a .travis.yml
