### ISSUE TITLE
non printable characters

### ISSUE THREAD

**Issue by ghost** [Terodom/termNote#11]
You should check for non printable characters, because they can mess up your terminal.
Even though this makes lists possible:

```termNote -a "$(printf 'list\x0B\rItem 1\x0B\rItem 2')"```
would result in
```
[0] list
Item 1  
Item 2
```
But I don't thinks that's an intended behavior

**Comment by ghost** [comment]
I personally would say this is expected behaviour, if the user intentionally puts in non printable characters it's the users fault not the software.

**Comment by balsoft** [comment]
> I personally would say this is expected behaviour, if the user intentionally puts in non printable characters it's the users fault not the software.

I think that needs to be a config option. If user is advanced enough to use non-printable characters, they might as well just change one line of configuration. If it's not set, termNote should warn you when you try to add a note with unprintable characters.

**Comment by ghost** [comment]
The normal user will most lukely not enter a unprintable char we cant save the user from himself.

**Comment by ghost** [comment]
IMO @Terodom is right here.
You can't accidentally enter non printable characters.
I can't think of an input that would affect other notes than the one entered, so i guess it's fine.

**Comment by balsoft** [comment]
I think this can be closed then?
