### ISSUE TITLE
Todo.txt support

### ISSUE THREAD

**Issue by balsoft** [Terodom/termNote#16]
How about adding some simple todo.txt support? For example:
- instead of deleting notes, we can mark them as complete (`x` in Todo.txt format)
- sort them according to priority instead of by the order they were created in; 
- add creation date and completion date so that we can filter them by date;
- filter, group complete and delete them by projects (`+ProjectName`) and contexts (`@ContextName`).

**Comment by ghost** [comment]
Sounds like a neat idea for 2.0
