### ISSUE TITLE
Use nix to create distribution-independent binary releases (or AppImages)

### ISSUE THREAD

**Issue by balsoft** [Terodom/termNote#22]
There is a wonderful project, [nix-bundle](https://github.com/matthewbauer/nix-bundle), which allows to create distribution-independent executables with arx from nix expressions. I have created some sample [executables (google drive, 35MB, zip)](https://drive.google.com/file/d/1t25dpc7yz-QLvaxcONjRrCfTwuNJxx32/view?usp=sharing) from `master`, which I encourage you to try and run on your distro. In theory, all it takes to run is to mark them as executable. Unfortunately, they're quite slow and big as they need to carry all the dependencies with them. `nix-bundle` also provides some support functions to create AppImages, which would be much faster, but they need additional work to be built.

**Comment by balsoft** [comment]
It looks like building AppImages requires a `.desktop` file. I think it would be a good idea to add them anyways (one for `termNote`, one for `noted`).

**Comment by balsoft** [comment]
I think I can build AppImages now. I am going to test everything to see if it works (AppImages don't work on NixOS by default, I'll have to install some additional scripts to test them)

**Comment by balsoft** [comment]
I get some strange errors. Still, here's an [AppImage](https://drive.google.com/file/d/1f9Rw41lurrQl0-pejAHD0WiwgH3jmCDW/view?usp=sharing) for termNote (the executable itself; I can also build an AppImage for noted, but it has strange errors as well).

**Comment by balsoft** [comment]
Well, I don't know how to fix errors with AppImages, but I've got bundles to be smaller and run faster. Maybe they're good enough for the first couple of releases?
Going for a PR.

**Comment by balsoft** [comment]
We can automatically add releases from travis: https://docs.travis-ci.com/user/deployment/releases/
On the nix side, that will mean something like
```yaml
language: nix
script:
  - nix-build 
  - nix-build -A bundles.termNote -o termNote 
  - nix-build -A bundles.noted -o noted
deploy:
  # Other setup here
  file:
    - noted
    - termNote
```
(Although I am not sure script can be a list)

**Comment by balsoft** [comment]
Verified that bundles work on Tiny Core Linux 64 bit. That probably means that they work practically everywhere.

**Comment by ghost** [comment]
Will test on Arch, altho i couldn't get nix itself to work.

**Comment by balsoft** [comment]
> i couldn't get nix itself to work.

What did you do and what was the problem? Last time I tried to run nix on arch it worked fine (I think that was summer of 2018). `curl https://nixos.org/nix/install | sh` worked for me.

**Comment by balsoft** [comment]
Anyways, it seems automatic travis deploys are working! https://github.com/balsoft/termNote/releases/tag/v1.2.4
Please see .travis.yml from my fork to see what's going on. I recommend running `travis setup releases` first, then edit the resulting file manually (importantly, add `file`, `draft` and `skip_cleanup`).

**Comment by ghost** [comment]
How do these work? does it create an automatic release when you push a new tag? also, i don't quite get what you mean with running `travis setup releases`

**Comment by balsoft** [comment]
With configuration that I used, it makes a release for every build, but it puts them in drafts so that you can manually un-draft them. You can also make releases when tags are pushed by adding 
```yaml
deploy:
  on:
    tags: true
``` 
to .travis.yml
> travis setup releases

`travis` is a CLI utility that allows you to configure .travis.yml automatically (e.g. it added the api_key token in my .travis.yml)
I got it from nixpkgs, but it can be installed from AUR, I suppose.

**Comment by ghost** [comment]
Will look into it tomorrow.

**Comment by balsoft** [comment]
Do bundles work for you on arch? They give some strange errors in Virtualbox liveISO. 
```
$ wget https://github.com/balsoft/termNote/releases/download/v1.2.3/termNote
$ chmod +x termNote
$ ./termNote
terminate called after throwing an instance of 'std::experimental::filesystem::v1::__cxx11::filesystem_error'
   what():  filesystem error: cannot create directory: No such file or directory [/root/.termNote/]
```
I don't know if that comes from glibc version mismatch, or some other cause.

**Comment by balsoft** [comment]
Hmm, it seems to be kind of deliberate - it runs termNote in sandbox essentially, thus limiting it's abilities to read/write. Investigating right now.

**Comment by balsoft** [comment]
https://github.com/matthewbauer/nix-bundle/issues/33 seems to be the issue here.

**Comment by balsoft** [comment]
Ah. It looks like it fails because `/root` is not passed through to sandbox, while `/home` is. That's why it worked in tiny core - you are logged in as non-root user there by default.

**Comment by balsoft** [comment]
https://github.com/matthewbauer/nix-bundle/pull/43 is the solution.
